- name: disable default redis
  ansible.builtin.command: dnf module disable redis -y
- name: disable enable redis
  ansible.builtin.command: dnf module enable redis:7 -y


- name: install redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: allaow remote access
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'  
    replace: '0.0.0.0' 

- name: disable protected mode
  ansible.builtin.lineinfile: #for line replace
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'  
    line: 'protected-mode no'        

- name: enable redis
  ansible.builtin.service:
    name: redis
    state: restarted
    enabled: yes     