- name: copy mongo.repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb
  ansible.builtin.dnf:
    name: mongodb-org 
    state: present    
        
- name: Allow remote access
  ansible.builtin.replace: #word replace
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'   

- name: start mongodb service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes   