- name: install mysql 
  ansible.builtin.dnf: 
    name: mysql-server
    state: present

- name: start & enable mysql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setup root password
  ansible.builtin.shell:  mysql_secure_installation --set-root-pass RoboShop@1 