- name: app-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: nodejs-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml   

- name: copy mongo.repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mogodb client
  ansible.builtin.package:
    name:  mongodb-mongosh
    state: present

- name: check products loaded
  ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print the output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load the products 
  ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
  when: catalogue_output.stdout  | int < 0  #if less than 0 load products(index/integer)

- name: system-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml
  
