- name: create system user for run app with nonroot access
  ansible.builtin.user:
    name: roboshop
    comment: roboshop system user
    system: true
    shell: /sbin/nologin
    home: /app

- name: remove app directory
  ansible.builtin.file:
    state: absent
    path: /app

- name: create directory
  ansible.builtin.file:
    state: directory
    path: /app
    
- name: delete {{ component }} file
  ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent

- name: download {{ component }}  application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /tmp/{{ component }}.zip

- name: unzip code
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes